nome = str(input('Como é o seu nome? '))
metros = int(input('Quantos metros você quer? '))
km = (metros / 1000)
hm = (metros / 100)
dam = (metros / 10)
dm = (metros * 10)
cm = (metros * 100)
mm = (metros * 1000)
milha = (metros / 1609)
jarda = (metros * 1094)
pé = (metros * 3281)
polegadas = (metros * 39.37)
print('{} Metros em Kilômetros fica {:.3f} \n {} Metros em Hectômetros fica {:.3f} \n {} Metros em Decâmetros fica {:.3f} \n {} Metros em Decímetros fica {:.3f} \n {} Metros em Centímetros fica {:.3f} \n {} Metros em Milímetros fica {:.3f} \n {} Metros em Milhas fica {:.2f} \n {} Metros em Jardas {:.2f} \n {} Metros em "Pé" fica {:.2f} \n {} Metros em Polegadas fica {:.2f}'.format(metros, km, metros, hm, metros, dam, metros, dm, metros, cm, metros, mm, metros, milha, metros, jarda, metros, pé, metros, polegadas))
