name = str(input('Como é o seu nome completo? ')).strip()
print('Seu Nome Normal: {}'.format(name))
print('')
print('Seu Nome em Maiúsculo: {}'.format(name.upper()))
print('')
print('Seu Nome em Minúsculo: {}'.format(name.lower()))
print('')
divided = (name.split())
# print('O seu nome virou uma lista por causa do comando Split!', divided)
divided = ''.join(divided)
# print(divided)
# print('')
print('O Seu nome possuí {} Letras!'.format(len(divided)))
print('')
divdo = (name.split())
print('O seu primeiro nome tem {} Letras!'.format(len(divdo[0])))
print('*' * 10)
print('Seu nome possui {} Caracteres.'.format(len(name)-name.count(' ')))
