# N01 = int(input('Qual número você vai querer somar?'))
# N02 = int(input('E com qual número?'))
# SOMA = N01 + N02
# print(f'A soma entre os números {N01} e {N02} é igual à {SOMA}.')
nome = str(input('Como é o seu nome?'))
print(f'Seja bem-vindo(a), Lorde {nome}!')
NDI = input('Digite alguma coisa: ')
print('O tipo primitivo desse valor é ', type(NDI))
print('O que você digitou é Alfanumérico (ABC123):', NDI.isalnum())
print('O que você digitou é Numérico (123):', NDI.isnumeric())
print('O que você digitou é Alfabético (ABC):', NDI.isalpha())
print('O que você digitou é Assimétrico (AB04+25F):', NDI.isascii())
print('O que você digitou é um Dígito (0 - 9):', NDI.isdigit())
print('O que você digitou é um Decimal (Números fracionados, como 1,5 ou 10,9):', NDI.isdecimal())
print('O que você escreveu é um teste se é um identificador ou não, como Class ou Def:', NDI.isidentifier())
print('O que você escreveu são apenas palavras em minúsculas:', NDI.islower())
print('O que você escreveu pode ser Impresso:', NDI.isprintable())
print('o que você escreveu é um espaço (Como a função da barra de espaço do computador):', NDI.isspace())
print('O que você escreveu é um título (Ter somente a primeira letra em Maiúsculo):', NDI.istitle())
print('O que você escreveu está totalmente em Maiúsculo:', NDI.isupper())
